# Generated by Django 6.0.7 on 2026-07-14 03:54

from django.db import migrations, models


def backfill_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).update(role="ADMIN")
    User.objects.filter(is_superuser=False, is_staff=True).update(role="STAFF")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='MEMBER', max_length=16),
        ),
        migrations.RunPython(backfill_role, noop_reverse),
    ]
